DIG-1357, DIG-1356, DIG-1272: testing and refactor of htsget ingest
CanDIG/candigv2-ingest pull request #43
Opened 2023-11-15 08:01 UTC by daisieh

* Refactored htsget ingest to use our new json format
* Tweaked paths and input in openapi schema to remove specific MoH references
* Added basic tests for htsget ingest

NOTE: I need to add testing to validate that the files are accessible via htsget, so that the user can know if the ingest worked and if they need to add credentials to S3 if that's why it's not working. That should probably be a separate ticket.

2023-11-15 19:47 UTC, OrdiNeu approved these changes
Works and looks good to me!

2023-11-15 23:26 UTC, merged

2023-11-16 17:32 UTC, mshadbolt requested changes
I think we should change identifiers to make them consistent across genomic and clinical metadata.

I haven't tested the actual code because I can't get it to work on my machine as yet

2023-11-16 17:32 UTC, mshadbolt commented on ingest_openapi.yaml
> +        donor_sample_id:
I am wondering here if we should keep it to the same language as the clinical data to avoid confusion, i.e. `submitter_sample_id`

2023-11-16 17:32 UTC, mshadbolt commented on ingest_openapi.yaml
> +              description: which reference genome was used for alignment
```suggestion
              description: which reference genome was used for alignment (hg37 or hg38)
```

2023-11-16 17:32 UTC, mshadbolt commented on ingest_openapi.yaml
> +        donor_sample_id:
```suggestion
        submitter_sample_id:
```

2023-11-16 17:32 UTC, mshadbolt commented on tests/genomic_ingest.json
> +                "donor_sample_id": "SAMPLE_REGISTRATION_1"
If we change to submitter_sample_id we will need to edit the examples
```suggestion
                "submitter_sample_id": "SAMPLE_REGISTRATION_1"
```

2023-11-16 17:32 UTC, mshadbolt commented on tests/genomic_ingest.json
> +                "donor_sample_id": "SAMPLE_REGISTRATION_4"
```suggestion
                "submitter_sample_id": "SAMPLE_REGISTRATION_4"
```

2023-11-16 17:32 UTC, mshadbolt commented on README.md
> +                "donor_sample_id": "SAMPLE_REGISTRATION_1"   # The submitter_sample_id to link to
```suggestion
                "submitter_sample_id": "SAMPLE_REGISTRATION_1"   # The submitter_sample_id to link to
```

2023-11-16 17:32 UTC, mshadbolt commented on README.md
> +                "donor_sample_id": "SAMPLE_REGISTRATION_4"
```suggestion
                "submitter_sample_id": "SAMPLE_REGISTRATION_4"
```

2023-11-16 17:32 UTC, mshadbolt commented on README.md
> +				"donor_sample_id": "SPECIMEN_5"
```suggestion
				"submitter_sample_id": "SPECIMEN_5"
```